#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# add_banner_sshd plugin
#

source "utils/utils.sh"

DATE="$(date +%Y%m%d%H%M%S)"
SSHD_CONF="/etc/ssh/sshd_config"
BANNER_FILE="/etc/ssh/sshd-banner"
BANNER_TMP_CONF="conf_files/sshd-banner"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

add_banner_sshd() {
	utils.log "add_banner_sshd" "The banner will be located under ${BANNER_FILE}"
	[[ -f "${SSHD_CONF}" ]] || utils.die "${SSHD_CONF} does not exists"
	[[ -f "${BANNER_TMP_CONF}" ]] || utils.die "${BANNER_TMP_CONF} does not exists"

	if [[ -f "${BANNER_FILE}" ]]; then
		utils.log_warning "add_banner_sshd" "Found existing ${BANNER_FILE}"
		utils.log "add_banner_sshd" "Backing up:${BANNER_FILE} to:${BANNER_FILE}.${DATE}.bak"
		! "${DRY}" && cp "${BANNER_FILE}" "${BANNER_FILE}.${DATE}.bak"
		utils.log_ok "add_banner_sshd" "Backed up:${BANNER_FILE} to:${BANNER_FILE}.${DATE}.bak"
	fi

	utils.log "add_banner_sshd" "Installing ${BANNER_TMP_CONF} into ${BANNER_FILE}"
	! "${DRY}" && cp -f "${BANNER_TMP_CONF}" "${BANNER_FILE}"
	utils.log_ok "add_banner_sshd" "Installed ${BANNER_TMP_CONF} into ${BANNER_FILE}"

	if [[ $(grep "^#* *Banner .*$" "${SSHD_CONF}") != "" ]]; then
		! "${DRY}" && sed -i "s|^#* *Banner .*$|Banner ${BANNER_FILE}|" "${SSHD_CONF}"
	else
		! "${DRY}" && echo -e "Banner ${BANNER_FILE}" >> "${SSHD_CONF}"
	fi

	utils.log "add_banner_sshd" "Restarting sshd service"
	if ! service sshd restart >& /dev/null; then
		utils.log_error "add_banner_sshd" "Could not restart sshd service. A restart is required in order for changes to take effect"
	else
		utils.log_ok "add_banner_sshd" "Successfully added banner"
	fi
}

main() {
	utils.log_start_plugin "add_banner_sshd"

	parse_params "${@}"
	add_banner_sshd

	utils.log_end_plugin "add_banner_sshd"
}

main "${@}"
