#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# cron plugin
#

source "utils/utils.sh"

CRON_WHITE_LIST_FILE="/etc/cron.allow"
CRON_BLACK_LIST_FILE="/etc/cron.deny"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

main() {
	utils.log_start_plugin "cron"
	parse_params "${@}"
	./utils/cron_at.sh --whitelist="${CRON_WHITE_LIST_FILE}" \
				--blacklist="${CRON_BLACK_LIST_FILE}" \
				--component="cron" \
				--dry="${DRY}"

	utils.log_end_plugin "cron"
}

main "${@}"
