#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# disable root plugin
#

source "utils/utils.sh"

SSH_CONF="/etc/ssh/sshd_config"
RECONFIG_COMMAND='\n\n# Disabling root login\nPermitRootLogin no'

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

disable_root_login_sshd_login() {

	utils.log "disable_root_login_sshd" "Disabling root login"
	[[ -f "${SSH_CONF}" ]] || utils.die "${SSH_CONF} does not exists"

	if [[ $(grep "^#* *PermitRootLogin [a-z]\{2,3\}$" "${SSH_CONF}") != "" ]]; then
		! "${DRY}" && sed -i 's/^#* *\(PermitRootLogin\) [a-z]\{2,3\}$/\1 no/g' "${SSH_CONF}"
	else
		! "${DRY}" && echo -e "${RECONFIG_COMMAND}" >> "${SSH_CONF}"
	fi

	utils.log "disable_root_login_sshd" "Restarting ssh service"
	if ! service sshd restart >& /dev/null; then
		utils.log_error "disable_root_login_sshd" "Could not restart ssh service. A restart is required in order for changes to take effect"
	else
		utils.log_ok "disable_root_login_sshd" "Root login disabled"
	fi
}

main() {
	utils.log_start_plugin "disable_root_login_sshd"

	parse_params "${@}"
	disable_root_login_sshd_login

	utils.log_end_plugin "disable_root_login_sshd"
}

main "${@}"
