#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# disable_ipv6 plugin
#

source "utils/utils.sh"
MODPROBE_DIR="/etc/modprobe.d/"
NETWORK_CONF="network-hardening.conf"
NETWORK_SYS="/etc/sysconfig/network"
NETWORKING_SYS_PROPS=("NETWORKING_IPV6" "IPV6INIT")

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

update_network_sys() {
	for property in "${NETWORKING_SYS_PROPS[@]}"
	do
		if [[ $(grep "${property}" "${NETWORK_SYS}") == "" ]]; then
			utils.log "disable_ipv6" "Setting:${property}=no in:${NETWORK_SYS}"
			! "${DRY}" && echo "${property}=no" >> "${NETWORK_SYS}"
		else
			utils.log "disable_ipv6" "Changing ${property} to:${property}=no in:${NETWORK_SYS}"
			! "${DRY}" && sed -i 's/^\('$property'\)=.*/\1=no/g' "${NETWORK_SYS}"
		fi
	done
}

disable_ipv6() {

	utils.log "disable_ipv6" "Disabling disable_ipv6"
	[[ -d "${MODPROBE_DIR}" ]] || utils.die "${MODPROBE_DIR} does not exists"

	utils.log "disable_ipv6" "Disabling disable_ipv6 kernel module"
	! "${DRY}" && echo "install disable_ipv6 /bin/true" > "${MODPROBE_DIR}${NETWORK_CONF}"

	utils.log "disable_ipv6" "Disabling ip6tables service"
	! "${DRY}" && chkconfig ip6tables off

	utils.log "disable_ipv6" "Updating disable_ipv6 related values in ${NETWORK_SYS}"
	update_network_sys

	utils.log_ok "disable_ipv6" "disable_ipv6 will be disabled on reboot"
}

main() {
	utils.log_start_plugin "disable_ipv6"

	parse_params "${@}"
	disable_ipv6

	utils.log_end_plugin "disable_ipv6"
}

main "${@}"
