#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Disable interactive startup plugin
#

source "utils/utils.sh"

INIT_CONFIG="/etc/sysconfig/init"
SETTING="PROMPT=no"
SETTING_REGEX='PROMPT=.*'

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

disable_interactive_startup() {
	local need_to_change=false
	utils.log "disable_interactive_startup" "Checking interactive startup setting"
	utils.if_setting_exists "${INIT_CONFIG}" "${SETTING_REGEX}"
	local exist="${?}"

	if [[ "${exist}" -eq 0 ]]; then
		local set_value="$(grep "${SETTING_REGEX}" "${INIT_CONFIG}" | cut -d'=' -f2)"
		[[ "${set_value}" = "yes" ]] && need_to_change=true
	fi

	if "${DRY}"; then
		if "${need_to_change}" || [[ "${exist}" -ne 0 ]]; then
			utils.log_warning "disable_interactive_startup" "Interactive is not disabled. Need to disable"
		else
			utils.log_ok "disable_interactive_startup" "Interactive startup is already disabled. Nothing to do"
		fi

		return
	fi

	if "${need_to_change}"; then
		utils.log "disable_interactive_startup" "Found setting. Need to update ${INIT_CONFIG} with ${SETTING}"
		sed -i s/${SETTING_REGEX}/${SETTING}/g "${INIT_CONFIG}"
	elif [[ "${exist}" -ne 0 ]]; then
		utils.log "disable_interactive_startup" "Updating ${INIT_CONFIG} with ${SETTING}"
		echo "${SETTING}" >> "${INIT_CONFIG}"
	else
		utils.log_ok "disable_interactive_startup" "Interactive startup is already disabled"
	fi
}

main() {
	utils.log_start_plugin "disable_interactive_startup"

	parse_params "${@}"
	disable_interactive_startup

	utils.log_end_plugin "disable_interactive_startup"
}

main "${@}"
