#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# disable_ip_forwarding_sshd plugin 
#

source "utils/utils.sh"

SSH_CONF="/etc/ssh/sshd_config"
DISABLE_FEATURES=('AllowTcpForwarding' 'X11Forwarding')

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

disable_ip_forwarding_sshd() {

	utils.log "disable_ip_forwarding_sshd" "Disabling IP forwarding"
	[[ -f "${SSH_CONF}" ]] || utils.die "${SSH_CONF} does not exists"

	for forwarding in "${DISABLE_FEATURES[@]}";
	do
		if [[ $(grep "^#* *${forwarding} [a-z]\{2,3\}$" "${SSH_CONF}") != "" ]]; then
			utils.log "disable_ip_forwarding_sshd" "Setting ${forwarding} no"
			! "${DRY}" && sed -i 's/^#* *\('$forwarding'\) [a-z]\{2,3\}$/\1 no/g' "${SSH_CONF}"
			utils.log_ok "disable_ip_forwarding_sshd" "Set ${forwarding} no"
		else
			utils.log "disable_ip_forwarding_sshd" "Setting ${forwarding} no"
			! "${DRY}" && echo -e "\n\n# Disabling ${forwarding}\n${forwarding} no" >> "${SSH_CONF}"
			utils.log_ok "disable_ip_forwarding_sshd" "Set ${forwarding} no"
		fi
	done

	utils.log "disable_ip_forwarding_sshd" "Restarting ssh service"
	if ! service sshd restart >& /dev/null; then
		utils.log_error "disable_ip_forwarding_sshd" "Could not restart ssh service. A restart is required in order for changes to take effect"
	else
		utils.log_ok "disable_ip_forwarding_sshd" "Finished disabling IP forwarding"
	fi
}

main() {
	utils.log_start_plugin "disable_ip_forwarding_sshd"

	parse_params "${@}"
	disable_ip_forwarding_sshd

	utils.log_end_plugin "disable_ip_forwarding_sshd"
}

main "${@}"
