#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# enable_ip_forward
#

source "utils/utils.sh"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

enable_ip_forward() {

	utils.log "enable_ip_forward" "Set ip_forward parameter to 1 : Make communication possible between containers and the wider world."
	#Packets can only pass between containers if the 'ip_forward' parameter is set to 1
	if ! "${DRY}"; then
		sysctl -q net.ipv4.ip_forward=1
		sed -i "s/^net.ipv4.ip_forward = [0-9]*$/net.ipv4.ip_forward = 1/g" "/etc/sysctl.conf"
	fi

	utils.log_ok "enable_ip_forward" "Finished enabling ip forwarding Successfully"
}
main() {
	utils.log_start_plugin "enable_ip_forward"

	parse_params "${@}"
	enable_ip_forward

	utils.log_end_plugin "enable_ip_forward"
}

main "${@}"