#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# root_uid_validation plugin
#

source "utils/utils.sh"
PASSWD_FILE="/etc/passwd"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

enforce_uid() {
	utils.log "root_uid_validation" "Validating there is no other user with UID 0 execpt root"
	[[ -f "${PASSWD_FILE}" ]] || utils.die "${PASSWD_FILE} does not exists"

	UID_VALIDATION=($(cat "${PASSWD_FILE}" | cut -d: -f1,3 | grep ".*:0" | cut -d: -f1 | grep -v "root"))
	for username in "${UID_VALIDATION[@]}";
	do
		utils.log_error "root_uid_validation" "User - ${username} is with UID=0, locking this account"
		! "${DRY}" && usermod -L "${username}"
	done

	utils.log_ok "root_uid_validation" "UID validation complete"
}

main() {
	utils.log_start_plugin "root_uid_validation"

	parse_params "${@}"
	enforce_uid

	utils.log_end_plugin "root_uid_validation"
}

main "${@}"
