#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# SMTP configuration
#

source "utils/utils.sh"

POSTFIX_CONF='/etc/postfix/main.cf'


parse_params() {
	local all_params="${@?}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

add_replace_numeric_propety() {
	local key=${1?}
	local value=${2?}

	if [[ $(cat "${POSTFIX_CONF}" | grep "^#* *${key} = [0-9]*$") != "" ]]; then
		! "${DRY}" && sed -i "s/^#* *${key} = [0-9]*$/${key} = ${value}/" ${POSTFIX_CONF}
	else
		! "${DRY}" && echo -e "${key} = ${value}" >> "${POSTFIX_CONF}"
	fi
}


smtp_conf() {

	utils.log "SMTP_conf" "Configure SMTP through ${POSTFIX_CONF} file "

	[[ -f "${POSTFIX_CONF}" ]] || utils.die "${POSTFIX_CONF} does not exists"

	add_replace_numeric_propety 'default_process_limit' '100'
	add_replace_numeric_propety 'smtpd_client_connection_count_limit' '10'
	add_replace_numeric_propety 'smtpd_client_connection_rate_limit' '30'
	add_replace_numeric_propety 'queue_minfree' '20971520'
	add_replace_numeric_propety 'header_size_limit' '51200'
	add_replace_numeric_propety 'message_size_limit' '10485760'
	add_replace_numeric_propety 'smtpd_recipient_limit' '100'

	utils.log "SMTP_conf" "Restarting postfix service"
	service postfix restart
	if [[ "${?}" -ne 0 ]]; then
		utils.log_warning "SMTP_conf" "Could not restart postfix service. A restart is required in order for changes to take effect"
		return 1
	fi

	utils.log_ok "SMTP_conf" "Successfully configurd SMTP"
}

main() {
	utils.log_start_plugin "SMTP_conf"

	parse_params "${@}"
	smtp_conf

	utils.log_end_plugin "SMTP_conf"
}

main "${@}"

