#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# sudo plugin
#

source "utils/utils.sh"
source "utils/genpasswd.sh"
SUDO_CONF="/etc/sudoers"
ANSIBLE_GROUP="ansible_auto"
ANSIBLE_GID="2000"
ANSIBLE_SUDO="%${ANSIBLE_GROUP} ALL=(ALL) NOPASSWD: ALL"
DATE="$(date +%Y%m%d%H%M%S)"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

install_sudo() {

	! "${DRY}" && cp -f "${SUDO_CONF}" "${SUDO_CONF}.bak"

	utils.log "sudo" "Adding ${OPS_ADMIN_USER} to the system"
	if ! "${DRY}"; then
		if ! grep -q "^%${ANSIBLE_GROUP}" "${SUDO_CONF}"; then
			utils.log "sudo" "Adding group:${ANSIBLE_GROUP} to ${SUDO_CONF}"
			echo "${ANSIBLE_SUDO}" >> "${SUDO_CONF}"
			utils.log_ok "sudo" "Added group:${ANSIBLE_GROUP} to ${SUDO_CONF}"
		else
			utils.log_ok "sudo" "${ANSIBLE_GROUP} is already in ${SUDO_CONF}. Will apply new changes"
			sed -i "s/^%${ANSIBLE_GROUP}.*/${ANSIBLE_SUDO}/g" "${SUDO_CONF}"
		fi

		sed -i 's/Defaults.*env_reset/Defaults    !env_reset/g' "${SUDO_CONF}"
		sed -i 's/Defaults.*requiretty/Defaults    !requiretty/g' "${SUDO_CONF}"
	fi

	utils.log_ok "sudo" "plugin configuration finished"
}

main() {
	utils.log_start_plugin "sudo"

	parse_params "${@}"
	install_sudo

	utils.log_start_plugin "sudo"
}

main "${@}"
