#!/bin/bash

#
# hardening -- hardening tool for Linux servers
# Copyright (C) 2014-2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
#  Test plugin
#

source "utils/utils.sh"

parse_params() {
	local all_params="${@}"
	DRY="$(echo "${all_params}" | cut -d' ' -f1)"
}

run_plugin() {
	if "${DRY}"; then
		utils.log "test_plugin" "Dry mode detected"
	else
		utils.log "test_plugin" "Running test plugin"
	fi
}

main() {
	utils.log_start_plugin "test_plugin"

	parse_params "${@}"
	run_plugin

	utils.log_end_plugin "test_plugin"
}

main "${@}"
